name: Send Stripe DMs

on:
  schedule:
    - cron: '0 15 * * *'  # JST 24:00 = UTC 15:00
  workflow_dispatch:

jobs:
  send-dms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run DM sender
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_EVENT_DATABASE_ID: ${{ secrets.NOTION_EVENT_DATABASE_ID }}
          NOTION_ANSWER_DATABASE_ID: ${{ secrets.NOTION_ANSWER_DATABASE_ID }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_GUILD_ID: ${{ secrets.DISCORD_GUILD_ID }}
        run: python send_stripe_dms.py