name: Post Notion Events to Discord

on:
  schedule:
    - cron: '0 3 * * *'  # 毎日12:00 JST（UTC+9）
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python post_to_discord.py
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          NOTION_EVENT_DATABASE_ID: ${{ secrets.NOTION_EVENT_DATABASE_ID }}
          NOTION_ANSWER_DATABASE_ID: ${{ secrets.NOTION_ANSWER_DATABASE_ID }}
          DISCORD_CHANNEL_ID: ${{ secrets.DISCORD_CHANNEL_ID }}